name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Install dependencies
      run: |
        conda env create --file environment.yaml
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate ml-ids
        pip install -e .
    - name: Test with pytest
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate ml-ids
        python -m pytest tests
